### ISSUE TITLE
Compose question/answer textview does not scroll

### ISSUE THREAD

**Issue by billhanyu** [Jayyay/Duke-CSA-iOS#10]
I didn't copy the code from Rendezvous for this text view so for now when the length of the text is over a page when the keyboard pops up the text is hidden.

**Comment by Jayyay** [comment]
Why didn't you

**Comment by billhanyu** [comment]
cuz the compose view doesn't need the little box for input

**Comment by billhanyu** [comment]
Both the compose answer and the compose question textviews scroll when text overflows now. Although the content offset does not update with cursor position, I am lazy enough to call this a good enough solution.
